### ISSUE TITLE
Got compilation errors running the basic example

### ISSUE THREAD

**Issue by manell** [raphael/goa#115]
I'm trying to set up the basic example but I'm getting some errors due some bad imports.
```
package design

import (
        . "github.com/raphael/goa/design"
        . "github.com/raphael/goa/design/dsl"
)

var _ = API("cellar", func() {
        Title("The virtual wine cellar")
        Description("A basic example of an API implemented with goa")
        Scheme("http")
        Host("localhost:8080")
})

var _ = Resource("bottle", func() {
        BasePath("/bottles")
        DefaultMedia(BottleMedia)
        Action("show", func() {
                Description("Retrieve bottle with given id")
                Routing(GET("/:bottleID"))
                Params(func() {
                        Param("bottleID", Integer, "Bottle ID")
                })
                Response(OK)
                Response(NotFound)
        })
})

var BottleMedia = MediaType("application/vnd.goa.example.bottle+json", func() {
        Description("A bottle of wine")
        Attributes(func() {
                Attribute("id", Integer, "Unique bottle ID")
                Attribute("href", String, "API href for making requests on the bottle")
                Attribute("name", String, "Name of wine")
        })
        View("default", func() {
                Attribute("id")
                Attribute("href")
                Attribute("name")
        })
})
```

```
schema/schema.go:25: undefined: httprouter in httprouter.Router
app/contexts.go:73: undefined: fmt in fmt.Errorf
app/contexts.go:112: undefined: fmt in fmt.Errorf
app/media_types.go:17: imported and not used: "fmt"
```

In the scheme file, it's missing a httprouter import.
```
package schema

import (
	"github.com/raphael/goa"
)


// MountController mounts the API JSON schema controller under "/schema.json".
func MountController(service goa.Service) {
	ctrl := service.NewController("Schema")
	service.Info("mount", "ctrl", "Schema", "action", "Show", "route", "GET /schema.json")
	h := ctrl.NewHTTPRouterHandle("Show", getSchema)
	service.HTTPHandler().(*httprouter.Router).Handle("GET", "/schema.json", h)
}

```

In the contexts.go file it's missing the fmt import.

```
import (
	"github.com/raphael/goa"
	"strconv"
)
.
.
// OK sends a HTTP response with status code 200.
	func (ctx *ShowBottleContext) OK(resp *GoaExampleBottle) error {
	r, err := resp.Dump()
	if err != nil {
		return fmt.Errorf("invalid response: %s", err)
	}
	ctx.Header().Set("Content-Type", "application/vnd.goa.example.bottle+json; charset=utf-8")
	return ctx.JSON(200, r)
}

```

In the media_types.go the fmt package is not needed.

```
import (
	"github.com/raphael/goa"
	"fmt"
)
```

It seems to me that I misunderstood something. Does anyone know what I'm doing bad?

Thanks.

**Comment by raphael** [comment]
The code generation algorithms do their best efforts to compute the set of needed packages. There seems to be a few missing here and I'll create a PR shortly to address them. The case of "too many" imports is harder to deal with (sometimes `fmt` is needed sometimes it's not depending on how the types are defined in the DSL). There is logic though that should detect whether it's needed though - looks like it's missing a case.

While the generator code strives to generate the right imports (and if it doesn't it's generally a bug like the cases above) the saving grace is the use of `goimports`. Once the generator is done it invokes `goimport` on the files which both fixes up the formatting and the import clauses. I'm guessing that's why nobody else has reported these issues. So TL;DR it looks like for some reason `goimports` is not working properly here. Could you describe a little bit your Go setup? do you have multiple GOPATH? is `goimports` installed and in the PATH?

**Comment by manell** [comment]
goimports was not installed. I've installed the package running 
```go get golang.org/x/tools/cmd/goimports```  and now it's working.

Thanks for your time!

**Comment by raphael** [comment]
Great, thanks for confirming. I'll still update the generators code so they add the missing imports explicitly.

**Comment by raphael** [comment]
Added the missing imports and an explicit check for `goimports` in `goagen` so that this shouldn't happen anymore.
