### ISSUE TITLE
Can i serve index.html?

### ISSUE THREAD

**Issue by nizsheanez** [raphael/goa#126]
Hello, how can i serve index.html?

**Comment by raphael** [comment]
Use `service.ServeFiles`, for example here is what the `js` generator produces to serve the example HTML that loads the generated Javascript:
```go
	service.ServeFiles("/js/*filepath", http.Dir("/home/raphael/go/src/github.com/raphael/goa/examples/cellar/js"))
	service.Info("mount", "ctrl", "JS", "action", "ServeFiles", "route", "GET /js/*")
```

**Comment by nizsheanez** [comment]
I can serve /something/*filepath
But can't / or /*filepath

**Comment by raphael** [comment]
That's correct: if you could the router wouldn't know to route to the API controller or to a file on disk (so for example `/resources` could mean "render the file `resources.html`" or call the `GET` action on the `resources` resource). If you *need* `index.html` to be at the root, there are a few workarounds:
1. Define a top level resource (i.e. a resource with an empty `BasePath`) and a `GET` action that returns a redirect to the actual `index.html`.
2. Front your API with a load balancer / nginx / haproxy and have a rule there that rewrites the UI routes to the right place (probably the best approach in production).

**Comment by nizsheanez** [comment]
here is how `echo` solved it https://github.com/labstack/echo/blob/master/echo.go#L390

**Comment by raphael** [comment]
Thanks! Definitely something to ponder. I had seen how echo dealt with the issue and it's great that it lets you do that, on the other hand I'm not sure I like the "last route" wins strategy. echo will let you do something like:
```go
        e.ServeFile("/", "./index.html") // 1
        e.Get("/", hello)                        // 2
```
Everything will compile and run fine. What happens when you send a request to `/` depends on the order of `1` and `2` (here the API would win). `goa` takes a different approach where it will let you know if there are ambiguous routes. 

That being said the router could probably be made smarter and allow for common roots for both served files and API as long as the full path isn't ambiguous (basically adding a `ServeFile` a la `echo` vs. the current `ServeFiles`). Thanks for pushing this issue!

**Comment by nizsheanez** [comment]
Yes, also like detecting of ambiguous routes

**Comment by raphael** [comment]
I've modified `ServeFiles` to allow for common root paths between APIs and served files. Thank you again for raising this as it made the controllers that serve the Swagger spec and API JSON schema simpler.
